name: Build and Deploy

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
            java-version: '17.x'
            architecture: 'x64'
            node-version: 16

      - name: Build with Gradle
        run: ./gradlew

      - name: Authenticate with Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


      - name: Build and deploy APK
        run: |
          ./gradlew assembleRelease
          ./gradlew appDistributionUploadRelease --stacktrace
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
